### ISSUE TITLE
Doesn't work on text (.txt) files

### ISSUE THREAD

**Issue by haferburg** [bsegraves/custom-folds#6]
I have a file `atom.txt` on the desktop with the following contents:

    // <editor-fold>
    asdf
    asdf
    asdf
    asdf
    asdf
    // </editor-fold>
    
But nothing is happening when I hit `Ctrl+Shift+[` or use `RMB->Custom Folds->Fold All` or anything else. What am I missing here?

**Comment by haferburg** [comment]
Oh ok, it works when I change the file extension to .cpp. Why can't I use it on .txt files?

**Comment by bsegraves** [comment]
The plugin uses the language settings to determine the start of a comment.

With this approach, "// <editor-fold>" works in C++, JavaScript, etc, whereas "# <editor-fold>" works in Python, and so on.

Text files, though, don't technically have comments, and that's why they don't work within them.

**Comment by oldbie** [comment]
How difficult would it be to have it look within text files, either using a specific comment syntax or just looking for the defined fold strings? This would be super helpful for me for a number of text files I use for to do lists, snippets, etc. Renaming those files to a specific file type wouldn't make much sense.

Thanks for this package!

**Comment by jemshit** [comment]
yeah, i have stuck here

**Comment by bsegraves** [comment]
@oldbie Shouldn't be that hard to add. I'll take a look and will try and support this by the weekend.

**Comment by oldbie** [comment]
@bsegraves: Thanks! That'd be super helpful.

**Comment by bsegraves** [comment]
Version 1.9.0 released which fixes this.

Let me know if you run into any problems.

**Comment by jemshit** [comment]
Does not work on Atom 1.9.8, 1.10.2 Nothing happens when clicking fold all, unfold... except when clicking Fold Here : 
```
TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at atom-workspace.foldHere (/Users/codex/.atom/packages/custom-folds/lib/index.js:303:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by jemshit** [comment]
Still not working on atom 1.12.6

**Comment by dodekeract** [comment]
@jemshit @oldbie Are you aware that markdown exists? Just want to make sure, since it's a lot better than just using text files.

**Comment by oldbie** [comment]
@dodekeract: Yep. I use Markdown all the time.

**Comment by bsegraves** [comment]
@dodekeract Whoops. Yeah, we use a github enterprise at work and I pushed the commit with the wrong account. Thanks, I'll fix that!
